const actionTypes = {
    "IS_LOGIN": "IS_LOGIN",
    "ERROR": "ERROR",
    "LOADER": "LOADER",

    "LOGIN": "LOGIN",
    "LOGIN_DATA": "LOGIN_DATA",

    "SIGNUP": "SIGNUP",
    "SIGNUP_DATA": "SIGNUP_DATA",

    "GET_CURRENT_USER_DATAIL": "GET_USER_DEATAIL",
    "GET_CURRENT_USER_DATAIL_DATA": "GET_USER_DEATAIL_DATA",

    "UPDATE_USER_DETAIL": "UPDATE_USER_DETAIL",
    "UPDATE_USER_DETAIL_DATA": "UPDATE_USER_DETAIL_DATA",

    "GET_USER_PROFILE": "GET_USER_PROFILE",
    "GET_USER_PROFILE_DATA": "GET_USER_PROFILE_DATA",

    "FOLLOW_USER": "FOLLOW_USER",
    "FOLLOW_USER_DATA": "FOLLOW_USER_DATA",

    "UNFOLLOW_USER": "UNFOLLOW_USER",
    "UNFOLLOW_USER_DATA": "UNFOLLOW_USER_DATA",

    "ARTICLES_FROM_FOLLOWEES": "ARTICLES_FROM_FOLLOWEES",
    "ARTICLES_FROM_FOLLOWEES_DATA": "ARTICLES_FROM_FOLLOWEES_DATA",

    "GLOBAL_ARTICLES": "GLOBAL_ARTICLES",
    "GLOBAL_ARTICLES_DATA": "GLOBAL_ARTICLES_DATA",

    "CREATE_ARTICLES": "CREATE_ARTICLES",
    "CREATE_ARTICLES_DATA": "CREATE_ARTICLES_DATA",

    "GET_ARTICLES": "GET_ARTICLES",
    "GET_ARTICLES_DATA": "GET_ARTICLES_DATA",

    "UPDATE_ARTICLE": "UPDATE_ARTICLE",
    "UPDATE_ARTICLE_DATA": "UPDATE_ARTICLE_DATA",

    "DELECT_ARTICLE": "DELECT_ARTICLE",
    "DELECT_ARTICLE_DATA": "DELECT_ARTICLE_DATA",

    "GET_COMMENTS": "GET_COMMENTS",
    "GET_COMMENTS_DATA": "GET_COMMENTS_DATA",

    "ADD_COMMENTS": "ADD_COMMENTS",
    "ADD_COMMENTS_DATA": "ADD_COMMENTS_DATA",

    "DELETE_COMMENTS": "DELETE_COMMENTS",
    "DELETE_COMMENTS_DATA": "DELETE_COMMENTS_DATA",

    "FAV_ARTICLE": "FAV_ATICLE",
    "FAV_ARTICLE_DATA": "FAV_ATICLE_DATA",

    "UNFAV_ARTICLE": "UNFAV_ARTICLE",
    "UNFAV_ARTICLE_DATA": "UNFAV_ARTICLE_DATA",

    "GET_TAGS": "GET_TAGS",
    "GET_TAGS_DATA": "GET_TAGS_DATA",
}


export default actionTypes